import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import TopNavigation from "./components/TopNavigation";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400", // Add a valid weight value
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weather",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-screen ${poppins.variable} ${roboto.variable} antialiased bg-fade-top bg-fixed`}
      >
        <div className="flex flex-col h-full">
          <TopNavigation />
        <main className="flex-grow overflow-hidden">
          <div className="h-full overflow-auto p-4">{children}</div>
        </main>
        </div>
      </body>
    </html>
  );
}
